#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
osc99 = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'shell'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#0077c2'
    leading_diamond = '╭─'
    template = ' {{ .Name }} '

  [[blocks.segments]]
    type = 'root'
    style = 'diamond'
    foreground = '#FFFB38'
    background = '#ef5350'
    template = '<parentBackground></>  '

    [blocks.segments.properties]
      root_icon = ''

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#E4E4E4'
    background = '#444444'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#FFFB38'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#C792EA{{ end }}']
    template = ' {{ .HEAD }} {{ if .Working.Changed }}{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'node'
    style = 'diamond'
    foreground = '#3C873A'
    background = '#303030'
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a></> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#ffffff'
    background = '#40c4ff'
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' 󰃰 {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '3:04:05 PM'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#21c7c7'
    template = '╰─'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#e0f8ff'
    template = '❯{{ .String }} '

    [blocks.segments.properties]
      always_enabled = true
      display_exit_code = false
      error_color = '#ef5350'
